spring:

  devtools:
    add-properties: false

  datasource:
    url: "jdbc:mysql://localhost:3306/smartparkingbits"
    username: "root"
    password: ""

  jpa:
  
    hibernate:
      ddl-auto: update
      format_sql: true
      dialect: "org.hibernate.dialect.MySQL8Dialect"
    show-sql: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL     
  open-in-view: false


