spring:
  devtools:
    add-properties: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:springboot.db
    username: "admin"
    password: "admin"
  jpa:
    database-platform: "org.hibernate.dialect.SQLiteDialect"
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL